//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paying
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int ID_Categ { get; set; }
        public string Name { get; set; }
        public int Quality { get; set; }
        public decimal Price { get; set; }
        public decimal Sum { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
